In [8]:
import numpy as np
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x+y

array([3., 6., 9.])

In [5]:
x-y

array([-1., -2., -3.])

In [6]:
x*y

array([ 2.,  8., 18.])

In [7]:
x/y

array([0.5, 0.5, 0.5])

In [10]:
x = np.array([1.0, 2.0, 3.0])
x/2.0

array([0.5, 1. , 1.5])

In [13]:
A = np.array([[1,2], [3,4]])
print(A)

[[1 2]
 [3 4]]


In [14]:
A.shape

(2, 2)

In [15]:
A.dtype

dtype('int32')

In [16]:
B = np.array([[3,0],[0,6]])
A+B

array([[ 4,  2],
       [ 3, 10]])

In [17]:
A*B

array([[ 3,  0],
       [ 0, 24]])

In [18]:
print(A)

[[1 2]
 [3 4]]


In [19]:
A*10

array([[10, 20],
       [30, 40]])

In [20]:
A = np.array([[1,2], [3,4]])
B = np.array([10,20])
A*B

array([[10, 40],
       [30, 80]])

In [21]:
x = np.array([[51,55], [14,19], [0,4]])
print(x)

[[51 55]
 [14 19]
 [ 0  4]]


In [22]:
x[0]

array([51, 55])

In [23]:
x[0][1]

55

In [24]:
for row in x:
    print(row)

[51 55]
[14 19]
[0 4]


In [25]:
x = x.flatten() #x를 1차원 배열로 변환(평탄화)
print(x)

[51 55 14 19  0  4]


In [26]:
x[np.array([0,2,4])] # 인덱스가 0,2,4 인 원소표기

array([51, 14,  0])

In [27]:
x>15

array([ True,  True, False,  True, False, False])

In [28]:
x[x>15]

array([51, 55, 19])

In [33]:
x = np.array([0,1,2,3,4,5,6,7,8])
print(x.reshape(3,3))
x[x%2 == 0 ]*= -1
x

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([ 0,  1, -2,  3, -4,  5, -6,  7, -8])

In [37]:
simple_array = np.array([2.3, 0.1, -9.1])
simple_array[1:3]

array([0.1])

In [39]:
simple_array[3]

IndexError: index 3 is out of bounds for axis 0 with size 3